parameters:
#    i_spy_si_welcome.example.class: ISpySi\WelcomeBundle\Example

services:
#    i_spy_si_welcome.example:
#        class: %i_spy_si_welcome.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
