parameters:
#    i_spy_si_admin.example.class: ISpySi\AdminBundle\Example

services:
#    i_spy_si_admin.example:
#        class: %i_spy_si_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
