parameters:
#    i_spy_si_security.example.class: ISpySi\SecurityBundle\Example

services:
#    i_spy_si_security.example:
#        class: %i_spy_si_security.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
