ISpySi\WelcomeBundle\Entity\Work:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    name:
      type: string
      length: 255
    url:
      type: string
      length: 255
      nullable: true
    description:
      type: text
    imageName:
      type: string
      length: 255
      nullable: true
    dateAdded:
      type: date
    dateModified:
      type: date
      nullable: true
      #gedmo:
      #  timestampable:
      #    on: update
  lifecycleCallbacks: {  }
