parameters:
#    i_spy_si_user.example.class: ISpySi\UserBundle\Example

services:
#    i_spy_si_user.example:
#        class: %i_spy_si_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
